name: "SAMM PDF generator creator"
description: "Create the SAMM PDF from model files"
author: "SAMM core team"
branding:
  icon: 'package'
  color: 'blue'

inputs:
  keep_alive:
    description: 'Docker keep alive'
    required: true
    default: '1'
  url:
    description: 'The URL of the repository'
    required: true
  branch:
    description: 'The branch of the repository'
    required: true
    default: 'main'
  model:
    description: 'The model'
    required: true
    default: 'model'
  language:
    description: 'The language'
    default: 'en'

runs:
  using: 'docker'
  image: 'docker://php:8.1'
  env:
    KEEP_ALIVE: ${{ inputs.keep_alive }}
    URL: ${{ inputs.url }}
    BRANCH: ${{ inputs.branch }}
    MODEL: ${{ inputs.model }}
    LANGUAGE: ${{ inputs.language }}
  entrypoint: 'sh'
  args:
    - '-c'
    - 'ls'
#    - '/app/scripts/generate_pdf.sh $URL $BRANCH $MODEL $LANGUAGE && cp /app/export/SAMM.pdf /github/workspace'