name: "SAMM PDF generator creator"
description: "Create the SAMM PDF from model files"
author: "SAMM core team"
branding:
  icon: 'package'
  color: 'blue'

inputs:
  keep_alive:
    description: 'Docker keep alive'
    required: true
    default: '1'
  url:
    description: 'The URL of the repository'
    required: true
  branch:
    description: 'The branch of the repository'
    required: true
    default: 'main'
  model:
    description: 'The model'
    required: true
    default: 'model'
  language:
    description: 'The language'
    default: 'en'

runs:
  using: 'docker'
  image: 'docker://php:8.1'
  env:
    KEEP_ALIVE: ${{ inputs.keep_alive }}
    URL: ${{ inputs.url }}
    BRANCH: ${{ inputs.branch }}
    MODEL: ${{ inputs.model }}
    LANGUAGE: ${{ inputs.language }}
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      mkdir -p /app
      cp -R /github/workspace /app
      cp /app/scripts/generate_pdf.sh /app
      cd /app
      chmod +x generate_pdf.sh
      apt-get update && apt-get install -y git
      git clone $URL /app/my_project && cd /app/my_project && git checkout $BRANCH
      php -d memory_limit=-1 /app/generate_pdf.sh $MODEL $LANGUAGE
      cp /app/my_project/export/SAMM.pdf /github/workspace
    --volume "${{ github.workspace }}:/github/workspace"
#    - '/app/scripts/generate_pdf.sh $URL $BRANCH $MODEL $LANGUAGE && cp /app/export/SAMM.pdf /github/workspace'