name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      keep_alive:
        description: 'docker keep alive'
        required: true
        default: 0
      url:
        description: 'The url of the repo'
        required: true
        default: https://github.com/owaspsamm/core.git
      branch:
        description: 'branch of the repo'
        required: true
        default: develop
      model:
        description: 'the model'
        required: true
        default: 'model'
      language:
        description: 'the language'
        required: true
        default: 'en'

permissions:
  contents: read

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Print Input
      run: echo "${{ inputs.url }}"
    - name: Create Database
      run: sh scripts/generate_pdf.sh -a ${{ inputs.keep_alive }} -u ${{ inputs.url }} -b ${{ inputs.branch }} -m ${{ inputs.model }}-l ${{ inputs.language }}
    - uses: actions/upload-artifact@v3
      with:
        name: samm.pdf
        path: export/SAMM.pdf
